version: '3'
services:
  python3:
    build:
      context: ./app/
    volumes:
      - ./app/code:/code
    container_name: 'python3'
    tty: true
    ports:
      - "8080:8000"
    # depends_on:
    #   - mysql_db
    # networks:
    #   - app-tier

    #   mysql_db:
    #     container_name: "mysql"
    #     image: mysql:latest
    #     ports:
    #       - "3307:3306"
    #     environment:
    #       MYSQL_ROOT_PASSWORD: root
    #       MYSQL_USER: user
    #       MYSQL_PASSWORD: password
    #       TZ: 'Asia/Tokyo'
    #     restart: always
    #     networks:
    #       - app-tier
    # networks:
    #   app-tier:
    #     driver: bridge
