# Generated by Django 3.2.14 on 2023-05-16 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_alter_blog_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('text', models.TextField(max_length=500, verbose_name='本文')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='日付')),
                ('image', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
